//
//  ShadowMap.FS
//  PiEngine
//
//  Created by PiConspiracy on 10/27/2018
//  Copyright 2018 DigiPen Institute of Technology. All rights reserved.
//

#version 330 core

//in  vec2 TexCoordOut;
//uniform sampler2D gShadowMap;
//
//layout (location = 0) out vec4 FragColor;

void main()
{

	//FragColor = vec4(gl_FragCoord.z,gl_FragCoord.z,gl_FragCoord.z,gl_FragCoord.z);
//	gl_FragDepth = gl_FragCoord.z /100.0f;
	//FragColor = vec4(1,0,0,1);  
//float Depth = texture(gShadowMap, TexCoordOut).x;
    //Depth = 1.0 - (1.0 - Depth) * 25.0;
	//FragColor = vec4(Depth);

}